### ISSUE TITLE
Compile Error 'Cannot implicitly conver type Microsoft.Graph.Message to graphconsoleapp.message'

### ISSUE THREAD

**Issue by GermanPearls** [microsoftgraph/msgraph-training-optimize-network-traffic#15]
Working through the exercise in the learning module 'Optimize Traffic with Microsoft Graph', unit 5 of 8: 'Exercise - Avoid throttling & implement throttling strategies' and receive an error trying to save/build console app.

Error on line 125, return line from this function:
```
    private static Message GetMessageDetail(GraphServiceClient client, string messageId)
    {
      // submit request to Microsoft Graph & wait to process response
      return client.Me.Messages[messageId].Request().GetAsync().Result;
    }
```

Error reads:
`Cannot implicitly convert type 'Microsoft.Graph.Message' to 'graphconsoleapp.Message' [graphconsoleapp]csharp(CS0029)`

Have attempted to copy and paste exactly from this example to rectify but error persists.

**Comment by jasonjoh** [comment]
Hi @GermanPearls sorry for the trouble. I'm guessing you did the first part of this exercise without the Graph SDK? If so, make sure you remove the Messages.cs file from your project.

**Comment by GermanPearls** [comment]
@jasonjoh Yes, thank you, that fixed it.

**Comment by jasonjoh** [comment]
Excellent!
